{% set name = "Office365-REST-Python-Client" %}
{% set version = "2.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Office365-REST-Python-Client-{{ version }}.tar.gz
  sha256: 66b1e4a488f1f783e1666905774a207050c12aa63c2a2676aa4d636ca183f188

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests
    - msal
    - pytz
    - typing-extensions >=4.0.0

test:
  imports:
    - office365
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vgrem/Office365-REST-Python-Client
  summary: Microsoft 365 & Microsoft Graph Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
    - rxm7706
