{% set name = "office365-rest-python-client" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/office365_rest_python_client-{{ version }}.tar.gz
  sha256: 3f95d29794ee0adc58e0b16f6574257c885c74af108e1789e4b3c286bc2ce5ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.5
    - python >={{ python_min }}
    - requests >=2.32.4,<3
    - msal >=1.28,<2
    - pytz >=2021.1
    - typing-extensions >=4.0.0

test:
  imports:
    - office365
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vgrem/Office365-REST-Python-Client
  summary: Microsoft 365 & Microsoft Graph Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
    - rxm7706
