{% set name = "office365-rest-python-client" %}
{% set version = "2.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/office365_rest_python_client-{{ version }}.tar.gz
  sha256: d25569e6e6e837eb137e84f9cf4a93a60ed9c909b31bbe467938517712142ecb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.0.0
    - python >={{ python_min }}
    - requests
    - msal
    - pytz
    - typing-extensions >=4.0.0

test:
  imports:
    - office365
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vgrem/Office365-REST-Python-Client
  summary: Microsoft 365 & Microsoft Graph Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
    - rxm7706
